---
title: "Testing the linearity of a model with SpeTestNP"
author: "Hippolyte Boucher"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction

In applied work, it is very common to perform ordinary least squares to evaluate the effect of a set of exogenous variables $x$ on an outcome $y$. This effect is usually assumed to be causal but it may only be an approximation of the regression function in which case counterfactual analysis will be flawed. Thus in the past forty years a literature on general specification tests has developed in order to know if a model is truly linear or not. SpeTestNP is a package which implements the heteroskedasticity-robust version of five specification tests of the linearity of the model.

The author of SpeTestNP is Hipppolyte Boucher and the maintainer is Pascal Lavergne. This vignette describes each test available in SpeTestNP and how to use SpeTestNP to test linearity in practice.

## Testing Linearity



## Installation

## Testing with `SpeTest`

## Other Features

## References

H.J. Bierens, ["Conistent Model Specification Test"](https://www.sciencedirect.com/science/article/pii/0304407682901051), *Journal of Econometrics*, 20 (1), 105-134

J.X. Zheng, ["A Consistent Test of Functional Form via Nonparametric Estimation Techniques"](https://econpapers.repec.org/article/eeeeconom/v_3a75_3ay_3a1996_3ai_3a2_3ap_3a263-289.htm), *Journal of Econometrics*, 75 (2), 263-289

J. C. Escanciano, ["A Consistent Diagnostic Test for Regression Models Using Projections"](https://www.jstor.org/stable/4093212), *Econometric Theory*, 22 (6), 1030-1051

P. Lavergne and V. Patilea, ["Breaking the Curse of Dimensionality in Nonparametric Testing"](https://www.sciencedirect.com/science/article/pii/S0304407607001601), *Journal of Econometrics*, 143 (1), 103-122

P. Lavergne and V. Patilea, ["One for All and All for One: Regression Checks with Many Regressors"](https://www.tandfonline.com/doi/full/10.1198/jbes.2011.07152), *Journal of Business & Economic Statistics*, 30 (1), 41-52
